package com.github.madoc.create_sbt_project.model

import org.scalatest.{FreeSpec, Matchers}

class GitIgnoreTest extends FreeSpec with Matchers {
  "basic test" in {
    val gitIgnore = GitIgnore(Set(".idea", ".idea_modules", ".c9", "*.iml", "target", "out", "project/target",
      "project/project", "project.vim", "*~", "*#", ".DS_Store", "src/autogenerated"))
    gitIgnore.toString should be (
      """*#
        |*.iml
        |*~
        |.DS_Store
        |.c9
        |.idea
        |.idea_modules
        |out
        |project.vim
        |project/project
        |project/target
        |src/autogenerated
        |target
        |""" stripMargin
    )
  }
}
